language: node_js
sudo: false
node_js:
- 'node'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn run build