language: node_js
dist: trusty
sudo: false
node_js:
  - '9.7.0'

addons:
  chrome: stable

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - yarn

jobs:
  include:
    - stage: test
      script:
        - yarn build:@alyle/ui
        - yarn size-limit
    - stage: test
      script:
        - ng build alyle-ui
    - stage: deploy
      script:
        - yarn build
        - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn firebase deploy --token $FIREBASE_TOKEN --non-interactive || echo ''

stages:
  - test
  - deploy

