language: node_js
dist: trusty
sudo: false
node_js:
  - '9.7.0'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn

jobs:
  include:
    - stage: test
      script:
        - yarn amb
        - yarn size-limit
    - stage: test
      script:
        - ng build
    - stage: deploy
      script:
        - yarn build
        - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn firebase deploy --token $FIREBASE_TOKEN --non-interactive || echo ''

stages:
  - test
  - deploy
