language: node_js
dist: trusty
sudo: false
node_js:
  - '10.9.0'

# addons:
#   chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - dist

branches:
  only:
    - master

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

jobs:
  include:
    - stage: prepare
      script:
        - printenv
        - yarn build:tools
        - yarn tools:prepare-lib
    - stage: build
      script:
        - yarn build:@alyle/ui
        - yarn bundlesizelimit
    - stage: build
      script:
        - yarn ng build alyle-ui --aot --output-path dist/alyle-ui-aot
        - yarn build

stages:
  - prepare
  - build

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1a51030c5bebfd74da7a
    on_success: always
    on_failure: never
    on_start: never
