language: node_js
dist: trusty
sudo: false
node_js:
  - '10.0.0'

addons:
  chrome: stable

env:
  - STATUS=BUILD
  - STATUS=DEPLOY

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - yarn

jobs:
  include:
    - stage: build
      script:
        - yarn build:@alyle/ui
        - yarn size-limit
      env: STATUS=BUILD
    - stage: build
      script:
        - yarn ng build alyle-ui --aot
      env: STATUS=BUILD
    - stage: deploy
      script:
        - yarn build
        - yarn tools:deploy
      env: STATUS=DEPLOY

stages:
  - build
  - deploy

