language: node_js
dist: trusty
sudo: false
node_js:
  - '10.0.0'

addons:
  chrome: stable

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - yarn

jobs:
  include:
    - stage: build
      script:
        - yarn build:@alyle/ui
        - yarn size-limit
    - stage: build
      script:
        - yarn ng build alyle-ui --aot
    - stage: deploy
      script:
        - yarn build
        - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn firebase deploy --token $FIREBASE_TOKEN --non-interactive || echo ''

stages:
  - build
  - deploy

