language: node_js
sudo: false
node_js:
- '8.4.0'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"

branches:
  only:
    - master

install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn install
        - echo Hello World
    - stage: deploy
      script:
        - yarn functions:install
        - yarn build
        - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn firebase deploy --token $FIREBASE_TOKEN --non-interactive || echo ''

stages:
  - test
  - deploy
