# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr: none

jobs:

- job: Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
  - script: |
      sh ci/scripts/release.sh
    displayName: Release
