variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
- job: DeployPr
  displayName: Deploy Pull Request
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: WebApp
  - task: NodeTool@0
    inputs:
      versionSpec: '12.13.x'
  - script: |
      set -e
      curl -o- -L https://yarnpkg.com/install.sh | bash
    displayName: "Install Yarn"
  - task: CacheBeta@1
    inputs:
      key: yarn | $(Agent.OS) | yarn.lock
      path: $(YARN_CACHE_FOLDER)
    displayName: "Cache Yarn packages"
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        set -e
        yarn --frozen-lockfile
      noRc: false
    displayName: "Install Dependencies"
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        set -e -o pipefail

        . ci/setup.sh

        echo hi
      noRc: false
